### ISSUE TITLE
Feature Request: Extend Modal Functionality to Include Withdrawals Mango Modal

### ISSUE THREAD

**Issue by Redfox** [theworkdao/governance-ui#1]
# Feature Request: Extend Modal Functionality to Include Withdrawals Mango Modal

## Description

Currently, mango modal only supports deposit transactions. This limitation restricts users from performing a crucial operation: withdrawals. To enhance user experience and provide comprehensive transactional capabilities, it's essential to expand the modal's functionality.

## Proposed Changes

- **Introduce a Selection Mechanism**: Allow users to toggle between deposit and withdrawal operations within the modal. 

- **Account Selection**: Users should be able to choose the account they wish to deposit into or withdraw from. Since the deposit functionality already allows for account selection, this mechanism can be extended to support withdrawals as well.

- **Amount Entry**: The existing input field for specifying the deposit amount can be reused. For withdrawals, ensure that input validation checks for available balance to prevent overdraft scenarios.

## Expected Benefits

- **Enhanced User Experience**: By enabling both deposits and withdrawals, we provide a more complete and convenient service, reducing the need for users to navigate away from the modal for different transaction types.

- **Increased Engagement**: Offering a full suite of transactional operations could lead to increased user engagement and satisfaction, as users find more value in our application.

- **Operational Efficiency**: Consolidating transaction types within a single modal streamlines the user interface and simplifies the transaction process, potentially reducing user errors and support requests.

**Comment by OmBudhiraja** [comment]
Hi, I am interested in implementing this feature. Could you please direct me to some documentation for mango. I cannot find documentation for any method to facilitate withdrawals

**Comment by Redfox** [comment]
> Hi, I am interested in implementing this feature. Could you please direct me to some documentation for mango. I cannot find documentation for any method to facilitate withdrawals

mango has this [lib doc](https://blockworks-foundation.github.io/mango-client-v3/), just has to change the modal from [this file](https://github.com/solana-labs/governance-ui/blob/main/components/TreasuryAccount/MangoModal.tsx)
